language: shell
script: bash update_reminder.sh
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
      - secure: Frvagc2HO1eK+6Mp1S9slmkH1qDNnQlgtp421wsjqgPk7Cb+4VhpXB7ARhCBPvI1kyRU2DL5efE1WJR3KkZ8qbG6DelVkXLcVhvB9Q42ivJMEhTkN4S8shy2dd13SA9OxPT87nsbp/o+ElFYc9r059ZXSz9ANTF/oIB6SQke+8+7J81qWVOpzIYpo5r7wqfKyqA5bpVmyvSiFviWVdCS97AwwCbJp2ylpawRaqdu/qkaSKFhhrZFZY/2aECIbx64rE+VzB1s/KZHJWtxnJSgQdUcHjT8pbIW2v7eq5b8nRtWpKvLQ50r4YnrOjXYjYRSrwRFUJqEHoF8DOTvdoV6luS9tmyaSbcedTyZbdSsqOjdzc44qtsDKxjcr3OlT7+g0WBT9mAFztcwxMfOuB6E0QtFPbaI4aXKAAkNdw5wMKC9JY6CUStr1d8Nr05zc9dgrm/5D/EblvWJ1hFyoBhgIZrC3alwFGK7wPfvza/jRpojHIVfy27T5gloC0pGmKe0Au4u/bdIcMNmq1JfjSeGSwVAspRVN9K4ar0oegJIFSXqzRuNw3q4lJBmBiEGepW9/laTBEQFHCHb6vWTBBFW4oL6YQr3StJH5BIYZk69pEIXXZvwx+p6fICzUUpo23tcW2ts+EqjTLhheiKP5ZBrt2leuJBYDhk6eUlNQuVr/uQ=
    on_success: never
    on_failure: always
